#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!

#SBATCH --job-name=${JOB_NAME}
#SBATCH --output=${LOG_PATH}
#SBATCH --account=${ACCOUNT}
#SBATCH --partition=${PARTITION}
#SBATCH --time=12:00:00
${GIVEN_NODE}
### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=${NUM_NODES}
#SBATCH --cpus-per-task=${NUM_CPUS}
#SBATCH --mem=${MEMORY}
####SBATCH --exclusive
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=${NUM_GPUS_PER_NODE}

## Specify the working directory for this job
#SBATCH --chdir=${DIR}

# Load modules or your own conda environment here
# module load pytorch/v1.4.0-gpu

source ~/.bashrc
#${CONDA_PATH}
conda activate ${CONDA_ENV}

# ===== Call your code below =====
${COMMAND_PLACEHOLDER}
