name: MobileSensingSuite
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - click=7.1
  - Sphinx
  - python-dotenv>=0.5.1
  - pyarrow=3.0.0
  - numpy=1.20
  - pandas=1.2
  - scikit-learn=0.24
  - scipy=1.6.0
  - pylint=2.7.2
  - fastparquet
  - ipython
  - torchvision
  - graphviz
  - pytorch
  - cudatoolkit=10.2
  - jupyter
  - matplotlib
  - pytorch-lightning[extra]
  - torchmetrics>=0.5
  - pyspark=3.1.2
  - jsonargparse[all]
  - pip:
    - torchviz==0.0.2
    - pyyaml==5.4.1
    - wandb
    - xgboost==1.4.2
    - tensorboard==2.6.0
    - tabulate==0.8.9
    - petastorm==0.11.3
variables:
  USE_TORCH: 1
