class_path: src.models.models.CNNToTransformerClassifier
init_args:
  num_attention_heads: 4
  num_hidden_layers: 4
  kernel_sizes:
  - 5
  - 3
  - 1
  out_channels:
  - 256
  - 128
  - 64
  stride_sizes:
  - 2
  - 2
  - 2
  dropout_rate: 0.3
  num_labels: 2
  positional_encoding: false
  bootstrap_val_metrics: true
  warmup_steps: 0