model:  
  class_path: src.models.models.TransformerClassifier
  init_args:
    num_attention_heads: 4
    num_hidden_layers: 2
    dropout_rate: 0.4
    num_labels: 2
    # bootstrap_val_metrics: true
    warmup_steps: 20