model:
  class_path: src.models.models.XGBoost
  init_args:
    use_label_encoder: false
    gpu_id: 0
    max_depth: 2
    objective: binary:logistic
    eval_metric: auc

#  Implementation of the scikit-learn API for XGBoost classification: https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.XGBClassifier
